name: "Test"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Write YAML"
        id: yaml-action
        uses: teunmooij/yaml@v1
        with:
          data: '{"version":"3.8","services":{"alpine":{"image":"alpine","command":"tail -f /dev/null"}}}'
          to-file: "docker-compose.yaml"

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          ssh_key: "${{ secrets.DOCKER_SSH_KEY }}"
          file: "docker-compose.yaml"
          name: "test-stack"

  test_registry_auth:
    name: "Test Registry Auth"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: actions_test.yml
          directory: ansible
          configuration: |
            [defaults]
            host_key_checking = False
          inventory: |
            ${{ secrets.DOCKER_HOST }}
          options: |
            --extra-vars ansible_ssh_user=${{ secrets.DOCKER_USER }} ansible_ssh_private_key_file=${{ secrets.DOCKER_SSH_KEY }}

      - name: "Write YAML"
        id: yaml-action
        uses: teunmooij/yaml@v1
        with:
          data: '{"version":"3.8","services":{"alpine":{"image":"localhost:5000/alpine","command":"tail -f /dev/null"}}}'
          to-file: "docker-compose.yaml"

      - name: "Test Local Action with Registry Auth"
        id: test
        uses: ./
        with:
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          ssh_key: "${{ secrets.DOCKER_SSH_KEY }}"
          file: "docker-compose.yaml"
          name: "test-private-stack"
          with_registry_auth: "true"

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "ShellCheck"
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: src
